"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// app.ts
const express = require("express");
const morgan = require("morgan");
const user_route_1 = require("./routes/user.route");
const auth_route_1 = require("./routes/auth.route");
const address_route_1 = require("./routes/address.route");
const deviceType_route_1 = require("./routes/deviceType.route");
const device_route_1 = require("./routes/device.route");
const geocode_route_1 = require("./routes/geocode.route");
const complaint_route_1 = require("./routes/complaint.route");
const service_route_1 = require("./routes/service.route");
const quote_route_1 = require("./routes/quote.route");
const subscription_route_1 = require("./routes/subscription.route");
const payment_route_1 = require("./routes/payment.route");
const self_route_1 = require("./routes/self.route");
const wallet_route_1 = require("./routes/wallet.route");
const notification_route_1 = require("./routes/notification.route");
const upload_route_1 = require("./routes/upload.route");
const chat_route_1 = require("./routes/chat.route");
const circle_route_1 = require("./routes/circle.route");
const config_route_1 = require("./routes/config.route");
const app = express();
app.use(morgan("dev"));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));
const BASE_URL = "/api/v2";
app.use(`${BASE_URL}/chat`, chat_route_1.default);
app.use(`${BASE_URL}/circle`, circle_route_1.default);
app.use(`${BASE_URL}/user`, user_route_1.default);
app.use(`${BASE_URL}/auth`, auth_route_1.default);
app.use(`${BASE_URL}/address`, address_route_1.default);
app.use(`${BASE_URL}/device-type`, deviceType_route_1.default);
app.use(`${BASE_URL}/device`, device_route_1.default);
app.use(`${BASE_URL}/geocode`, geocode_route_1.default);
app.use(`${BASE_URL}/service`, service_route_1.default);
app.use(`${BASE_URL}/quote`, quote_route_1.default);
app.use(`${BASE_URL}/complaint`, complaint_route_1.default);
app.use(`${BASE_URL}/subscription`, subscription_route_1.default);
app.use(`${BASE_URL}/payment`, payment_route_1.default);
app.use(`${BASE_URL}/me`, self_route_1.default);
app.use(`${BASE_URL}/wallet`, wallet_route_1.default);
app.use(`${BASE_URL}/notification`, notification_route_1.default);
app.use(`${BASE_URL}/upload`, upload_route_1.default);
app.use(`${BASE_URL}/config`, config_route_1.default);
// app.use(errorHandler);
exports.default = app;
//# sourceMappingURL=app.js.map